lib.name = pi2c_dac
class.sources = pi2c_dac.c 
common.sources = ../../drivers/src/dac.c ../../drivers/src/I2C.c
datafiles = pi2c_dac-help.pd
cflags=-I../../drivers/src
include ../Makefile.pdlibbuilder